services:

  ####################
  ###     Proxy    ###
  ####################
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      backend:
        ipv4_address: 172.16.1.5
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  ####################
  ###    Client    ###
  ####################

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "${CLIENT_HOST}:${CLIENT_PORT}"
    #    network_mode: "host"
    networks:
      backend:
        ipv4_address: 172.16.1.2

    environment:
      #      - WATCHPACK_POLLING=true
      VIRTUAL_HOST: www.habilidad.tk
      VIRTUAL_PORT: 80
    volumes:
      - ./client:/app/
      - /app/node_modules
    container_name: habilidad_client

  ####################
  ###   database   ###
  ####################

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.16.1.4
    container_name: habilidad_database

  ####################
  ###    Server    ###
  ####################

  server:
    depends_on:
      - database
    stdin_open: true
    env_file:
      - ./.env
    expose:
      - 5000
    build:
      dockerfile: Dockerfile
      context: ./server
    networks:
      backend:
        ipv4_address: 172.16.1.3
    volumes:
      - ./server:/app/
      - /app/node_modules
    container_name: habilidad_server

volumes:
  my-db:

networks:
  backend:
    ipam:
      config:
        - subnet: 172.16.1.0/16
          gateway: 172.16.1.1
