services:

  ####################
  ###    Client    ###
  ####################

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "${CLIENT_HOST}:${CLIENT_PORT}"
    network:
      backend:
        ipv4_address: 172.0.0.2

    environment:
      VIRTUAL_HOST: www.habilidad.tk
      VIRTUAL_PORT: 80
    volumes:
      - ./client:/app/
      - /app/node_modules
    container_name: client

  ####################
  ###   database   ###
  ####################

  database:
    image: mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
    ports:
      - "${DB_HOST}:${DB_PORT}"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.0.0.4
    container_name: database

  ####################
  ###    Server    ###
  ####################

  server:
    depends_on:
      - database
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "${SERVER_HOST}:${SERVER_PORT}"
    networks:
      backend:
        ipv4_address: 172.0.0.2
    volumes:
      - ./server:/app/
      - /app/node_modules
    container_name: server

volumes:
  my-db:


networks:
  backend:
    ipam:
      config:
        - subnet: 172.0.0.0/16
          gateway: 172.0.0.1
