// export const FORGET_PASSWORD = 'FORGET_PASSWORD'
export const SHOW_MODAL = 'SHOW_MODAL'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const LOGOUT = 'LOGOUT'

/*------------------------------------------------------------------------------------
USER RELATED
------------------------------------------------------------------------------------*/
export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const LOGIN_OTP_BEGIN = 'LOGIN_OTP_BEGIN'
export const LOGIN_OTP_SUCCESS = 'LOGIN_OTP_SUCCESS'
export const LOGIN_OTP_ERROR = 'LOGIN_OTP_ERROR'

export const CREATE_USER_BEGIN = 'CREATE_USER_BEGIN'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR'

export const GET_USER_BEGIN = 'GET_USER_BEGIN'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const DELETE_USER_BEGIN = 'DELETE_USER_BEGIN'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR'

export const RESET_PASSWORD_LINK_BEGIN = 'RESET_PASSWORD_LINK_BEGIN'
export const RESET_PASSWORD_LINK_SUCCESS = 'RESET_PASSWORD_LINK_SUCCESS'
export const RESET_PASSWORD_LINK_ERROR = 'RESET_PASSWORD_LINK_ERROR'

/*------------------------------------------------------------------------------------
COURSES RELATED
------------------------------------------------------------------------------------*/
export const GET_ALL_COURSES_BEGIN = 'GET_ALL_COURSES_BEGIN'
export const GET_ALL_COURSES_SUCCESS = 'GET_ALL_COURSES_SUCCESS'

// get course content for a single course
export const GET_ONE_COURSE_BEGIN = 'GET_COURSE_BEGIN'
export const GET_ONE_COURSE_SUCCESS = 'GET_COURSE_SUCCESS'
export const GET_ONE_COURSE_ERROR = 'GET_COURSE_ERROR'

export const GET_ALL_PURCHASED_COURSES_BEGIN = 'GET_ALL_PURCHASED_COURSES_BEGIN'
export const GET_ALL_PURCHASED_COURSES_SUCCESS = 'GET_ALL_PURCHASED_COURSES_SUCCESS'
export const GET_ALL_PURCHASED_COURSES_ERROR = 'GET_ALL_PURCHASED_COURSES_ERROR'

export const GET_ALL_POPULAR_COURSES_BEGIN = 'GET_ALL_POPULAR_COURSES_BEGIN'
export const GET_ALL_POPULAR_COURSES_SUCCESS = 'GET_ALL_POPULAR_COURSES_SUCCESS'
export const GET_ALL_POPULAR_COURSES_ERROR = 'GET_ALL_POPULAR_COURSES_ERROR'

export const GET_ALL_TOP_COURSES_BEGIN = 'GET_ALL_TOP_COURSES_BEGIN'
export const GET_ALL_TOP_COURSES_SUCCESS = 'GET_ALL_TOP_COURSES_SUCCESS'
export const GET_ALL_TOP_COURSES_ERROR = 'GET_ALL_TOP_COURSES_ERROR'

export const CREATE_COURSE_BEGIN = 'CREATE_COURSE_BEGIN'
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS'
export const CREATE_COURSE_ERROR = 'CREATE_COURSE_ERROR'

export const EDIT_COURSE_BEGIN = 'EDIT_COURSE_BEGIN'
export const EDIT_COURSE_SUCCESS = 'EDIT_COURSE_SUCCESS'
export const EDIT_COURSE_ERROR = 'EDIT_COURSE_ERROR'

export const GET_ALL_TOPICS_BEGIN = 'GET_ALL_TOPICS_BEGIN'
export const GET_ALL_TOPICS_SUCCESS = 'GET_ALL_TOPICS_SUCCESS'
