// export const FORGET_PASSWORD = 'FORGET_PASSWORD'
export const SHOW_MODAL = 'SHOW_MODAL'
export const CLEAR_VALUES = 'CLEAR_VALUES'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const DISPLAY_ALERT = 'DISPLAY_ALERT'

export const SET_USER_BEGIN = 'SET_USER_BEGIN'
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS'
export const SET_USER_ERROR = 'SET_USER_ERROR'

export const LOGOUT = 'LOGOUT'

export const CREATE_USER_BEGIN = 'CREATE_USER_BEGIN'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const DELETE_USER_BEGIN = 'DELETE_USER_BEGIN'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR'
