pipeline {
    options {
        disableConcurrentBuilds()
    }
    agent any
    // agent {
    //     docker {
    //         image 'node:lts-buster-slim'
    //         args '-p 3000:3000'
    //     }
    // }
    environment {
        CI = 'true'
    }
    stages {
        stage('OWASP Dependency Check'){
            steps{
                dependencyCheck additionalArguments: ''' -o ./ --format HTML --format XML --disableYarnAudit''', odcInstallation: 'DependencyCheck'
            }
        }
        stage('Build') {
            agent {
                docker {
                    image 'node:lts-buster-slim'
                    args '-p 3000:3000'
                }
            }
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'node:lts-buster-slim'
                    args '-p 3000:3000'
                }
            }
            steps {
                sh 'chmod +x -R ./jenkins/scripts'
                sh './jenkins/scripts/test.sh'
            }
        }
    }
    post {
		success {
			dependencyCheckPublisher pattern: 'dependency-check-report.xml'
		}
	}
}
